# arguments for dataset
dataset: doc
data_root: /kaggle/input/doc-data/2_DocumentSegmentation
# data_root: /kaggle/input/doc-infer/infer
nclass: 2
crop_size: 288

# arguments for training
epochs1: 100
epochs2: 50
batch_size: 4 # per GPU x 4 GPUs
lr: 0.00005
criterion:
  name: DiceCE
  kwargs:
    ignore_index: 255
    
conf_thresh: 0.95
