# arguments for dataset
dataset: doc
data_root: /u03/thanhnv/2_DocumentSegmentation
nclass: 2
crop_size: 308

# arguments for training
epochs1: 30
epochs2: 30
batch_size: 12 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False